version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  CODECOV_TOKEN:
    secure: qLTLWGSiBSBNf9rKPeQUX1me41EhF4tJ3HLaxaMWo9tjaHlO829TeuLLtlr5dRad
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- choco install codecov
build_script:
- cmd: >-
    dotnet build -c Release

    dotnet pack -c Release
test_script:
- cmd: dotnet test -c Release --no-build --no-restore --test-adapter-path:. --logger:Appveyor /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../lcov
- cmd: codecov -f "lcov.opencover.xml"
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: zT5PjZloU9HIMGHOVi/1/Mn+HDbUZGHCJvIEAfxdJ1E7Qt17Bbje2MtklFErXmtc
skip_commits:
  files:
    - '**/*.md'     